<?php

namespace App\Tests\Integration\Services\Databases;

use App\Exceptions\Repository\DuplicateDatabaseNameException;
use App\Exceptions\Service\Database\DatabaseClientFeatureNotEnabledException;
use App\Exceptions\Service\Database\TooManyDatabasesException;
use App\Models\Database;
use App\Models\DatabaseHost;
use App\Services\Databases\DatabaseManagementService;
use App\Tests\Integration\IntegrationTestCase;
use Illuminate\Database\Connection;
use Illuminate\Support\Facades\DB;
use Mockery\MockInterface;
use PHPUnit\Framework\Attributes\DataProvider;

class DatabaseManagementServiceTest extends IntegrationTestCase
{
    /**
     * Setup tests.
     */
    protected function setUp(): void
    {
        parent::setUp();

        config()->set('panel.client_features.databases.enabled', true);
    }

    /**
     * Test that the name generated by the unique name function is what we expect.
     */
    public function test_unique_database_name_is_generated_correctly(): void
    {
        $this->assertSame('s1_example', DatabaseManagementService::generateUniqueDatabaseName('example', 1));
        $this->assertSame('s123_something_else', DatabaseManagementService::generateUniqueDatabaseName('something_else', 123));
        $this->assertSame('s123_' . str_repeat('a', 43), DatabaseManagementService::generateUniqueDatabaseName(str_repeat('a', 100), 123));
    }

    /**
     * Test that disabling the client database feature flag prevents the creation of databases.
     */
    public function test_exception_is_thrown_if_client_databases_are_not_enabled(): void
    {
        config()->set('panel.client_features.databases.enabled', false);

        $this->expectException(DatabaseClientFeatureNotEnabledException::class);

        $server = $this->createServerModel();
        $this->getService()->create($server, []);
    }

    /**
     * Test that a server at its database limit cannot have an additional one created if
     * the $validateDatabaseLimit flag is not set to false.
     */
    public function test_database_cannot_be_created_if_server_has_reached_limit(): void
    {
        $server = $this->createServerModel(['database_limit' => 2]);
        $host = DatabaseHost::factory()->recycle($server->node)->create();

        Database::factory()->times(2)->create(['server_id' => $server->id, 'database_host_id' => $host->id]);

        $this->expectException(TooManyDatabasesException::class);

        $this->getService()->create($server, []);
    }

    /**
     * Test that a missing or invalid database name format causes an exception to be thrown.
     */
    #[DataProvider('invalidDataDataProvider')]
    public function test_empty_database_name_or_invalid_name_triggers_an_exception(array $data): void
    {
        $server = $this->createServerModel();

        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('The database name passed to DatabaseManagementService::handle MUST be prefixed with "s{server_id}_".');

        $this->getService()->create($server, $data);
    }

    /**
     * Test that creating a server database with an identical name triggers an exception.
     */
    public function test_creating_database_with_identical_name_triggers_an_exception(): void
    {
        $server = $this->createServerModel();
        $name = DatabaseManagementService::generateUniqueDatabaseName('something', $server->id);

        $host = DatabaseHost::factory()->recycle($server->node)->create();
        $host2 = DatabaseHost::factory()->recycle($server->node)->create();
        Database::factory()->create([
            'database' => $name,
            'database_host_id' => $host->id,
            'server_id' => $server->id,
        ]);

        $this->expectException(DuplicateDatabaseNameException::class);
        $this->expectExceptionMessage('A database with that name already exists for this server.');

        // Try to create a database with the same name as a database on a different host. We expect
        // this to fail since we don't account for the specific host when checking uniqueness.
        $this->getService()->create($server, [
            'database' => $name,
            'database_host_id' => $host2->id,
        ]);

        $this->assertDatabaseMissing('databases', ['server_id' => $server->id]);
    }

    /**
     * Test that a server database can be created successfully.
     */
    public function test_server_database_can_be_created(): void
    {
        $server = $this->createServerModel();
        $name = DatabaseManagementService::generateUniqueDatabaseName('something', $server->id);

        $host = DatabaseHost::factory()->recycle($server->node)->create();

        // CREATE DATABASE, CREATE USER, GRANT, FLUSH PRIVILEGES
        $this->fakeRemoteDatabaseConnection()
            ->shouldReceive('statement')->times(4)->andReturnTrue();

        $response = $this->getService()->create($server, [
            'remote' => '%',
            'database' => $name,
            'database_host_id' => $host->id,
        ]);

        $this->assertInstanceOf(Database::class, $response);
        $this->assertSame($response->server_id, $server->id);
        $this->assertMatchesRegularExpression('/^(u\d+_)(\w){10}$/', $response->username);
        $this->assertSame(24, strlen($response->password));

        $this->assertDatabaseHas('databases', ['server_id' => $server->id, 'id' => $response->id]);
    }

    /**
     * Test that an exception encountered while creating the database on the remote host
     * rolls the panel-side record back.
     */
    public function test_exception_encountered_while_creating_database_rolls_back(): void
    {
        $server = $this->createServerModel();
        $name = DatabaseManagementService::generateUniqueDatabaseName('something', $server->id);

        $host = DatabaseHost::factory()->recycle($server->node)->create();

        $this->fakeRemoteDatabaseConnection()
            ->shouldReceive('statement')->andThrow(new \BadMethodCallException());

        try {
            $this->getService()->create($server, [
                'remote' => '%',
                'database' => $name,
                'database_host_id' => $host->id,
            ]);
            $this->fail('Expected the remote statement exception to bubble up.');
        } catch (\BadMethodCallException) {
            // Expected.
        }

        $this->assertDatabaseMissing('databases', ['server_id' => $server->id]);
    }

    /**
     * The database services confirm access via DatabaseHost->buildConnection(), so fake the
     * remote connection while leaving the panel's own connection real.
     */
    private function fakeRemoteDatabaseConnection(): MockInterface
    {
        $connection = \Mockery::mock(Connection::class);

        $manager = \Mockery::mock(app('db'));
        $manager->shouldReceive('build')->andReturn($connection);
        DB::swap($manager);
        $this->app->instance('db', $manager);

        return $connection;
    }

    public static function invalidDataDataProvider(): array
    {
        return [
            [[]],
            [['database' => '']],
            [['database' => 'something']],
            [['database' => 's_something']],
            [['database' => 's12s_something']],
            [['database' => 's12something']],
        ];
    }

    private function getService(): DatabaseManagementService
    {
        return $this->app->make(DatabaseManagementService::class);
    }
}
